import Link from "next/link";
import { LayoutDashboard, Landmark, Plus, Sparkles } from "lucide-react";
import { requireAdmin } from "@/lib/auth";
import { LogoutButton } from "@/components/admin/LogoutButton";
export default async function AdminLayout({ children }: { children: React.ReactNode }) {
  await requireAdmin();
  return <div className="min-h-screen bg-background lg:grid lg:grid-cols-[260px_1fr]">
    <aside className="hidden border-r bg-slate-950 text-slate-100 lg:sticky lg:top-0 lg:flex lg:h-screen lg:flex-col">
      <Link href="/admin/dashboard" className="flex h-20 items-center gap-3 border-b border-white/10 px-6"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary text-white shadow-lg shadow-primary/20"><Landmark className="h-5 w-5" /></span><div><p className="font-bold">Pantau Pinjaman</p><p className="text-xs text-slate-400">Ruang pemberi pinjaman</p></div></Link>
      <nav className="flex-1 space-y-2 p-4"><p className="px-3 pb-2 text-[11px] font-semibold uppercase tracking-[.18em] text-slate-500">Menu utama</p><Link href="/admin/dashboard" className="flex items-center gap-3 rounded-xl bg-white/10 px-3 py-3 text-sm font-semibold text-white"><LayoutDashboard className="h-4 w-4 text-indigo-300" />Dashboard</Link><Link href="/admin/borrowers/new" className="flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium text-slate-300 transition hover:bg-white/5 hover:text-white"><Plus className="h-4 w-4" />Tambah peminjam</Link></nav>
      <div className="border-t border-white/10 p-4"><div className="mb-3 rounded-xl bg-white/5 p-3"><p className="flex items-center gap-2 text-xs font-medium text-slate-300"><Sparkles className="h-3.5 w-3.5 text-indigo-300" />Data tersimpan aman</p><p className="mt-1 text-[11px] leading-relaxed text-slate-500">Kelola pinjaman pribadi dalam satu tempat.</p></div><LogoutButton className="w-full justify-start text-slate-300 hover:bg-white/10 hover:text-white" /></div>
    </aside>
    <div className="min-w-0"><header className="sticky top-0 z-40 border-b bg-background/90 backdrop-blur-xl lg:hidden"><div className="flex h-16 items-center justify-between px-4"><Link href="/admin/dashboard" className="flex items-center gap-2.5 font-bold"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-white"><Landmark className="h-4 w-4" /></span>Pantau Pinjaman</Link><LogoutButton compact /></div><nav className="flex gap-2 overflow-x-auto border-t px-4 py-2"><Link href="/admin/dashboard" className="inline-flex items-center gap-2 whitespace-nowrap rounded-lg bg-accent px-3 py-2 text-xs font-semibold text-accent-foreground"><LayoutDashboard className="h-3.5 w-3.5"/>Dashboard</Link><Link href="/admin/borrowers/new" className="inline-flex items-center gap-2 whitespace-nowrap rounded-lg px-3 py-2 text-xs font-semibold text-muted-foreground hover:bg-muted"><Plus className="h-3.5 w-3.5"/>Tambah peminjam</Link></nav></header><main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8 xl:p-10">{children}</main></div>
  </div>;
}
