import Link from "next/link";
import { redirect } from "next/navigation";
import { ArrowRight, CheckCircle2, Landmark, LockKeyhole, Search, ShieldCheck, Sparkles, WalletCards } from "lucide-react";
import { getCurrentAdmin } from "@/lib/auth";

export default async function Home() {
  if (await getCurrentAdmin()) redirect("/admin/dashboard");
  return <main className="relative min-h-screen overflow-hidden bg-slate-950 text-white"><div className="absolute inset-0 opacity-30 page-grid"/><div className="absolute -left-32 top-20 h-80 w-80 rounded-full bg-indigo-600/30 blur-3xl"/><div className="absolute -right-24 bottom-0 h-96 w-96 rounded-full bg-violet-600/20 blur-3xl"/>
    <div className="relative mx-auto flex min-h-screen max-w-6xl flex-col px-5 py-6 sm:px-8"><header className="flex items-center justify-between"><Link href="/" className="flex items-center gap-3 font-bold"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary shadow-lg shadow-primary/30"><Landmark className="h-5 w-5"/></span>Pantau Pinjaman</Link><span className="hidden items-center gap-2 text-xs text-slate-400 sm:flex"><ShieldCheck className="h-4 w-4 text-emerald-400"/>Akses privat & aman</span></header>
      <section className="grid flex-1 items-center gap-12 py-16 lg:grid-cols-[1.05fr_.95fr]"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-indigo-400/20 bg-indigo-400/10 px-3 py-1.5 text-xs font-semibold text-indigo-200"><Sparkles className="h-3.5 w-3.5"/>Pinjaman pribadi, lebih teratur</div><h1 className="max-w-xl text-balance text-4xl font-bold leading-[1.08] sm:text-6xl">Catatan yang jelas, tanpa percakapan yang canggung.</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-300 sm:text-lg">Pantau pinjaman, pembayaran, dan bukti transfer dalam satu tempat yang bisa dilihat kedua pihak.</p><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-sm text-slate-400">{["Beberapa pinjaman per orang","Status real-time","Bukti transfer bersama"].map(item=><span key={item} className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-emerald-400"/>{item}</span>)}</div></div>
        <div className="grid gap-4"><Link href="/onboarding" className="group rounded-2xl border border-white/10 bg-white/[.07] p-6 shadow-2xl backdrop-blur transition hover:-translate-y-1 hover:border-indigo-400/40 hover:bg-white/[.1]"><div className="flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-indigo-500 text-white"><Search className="h-5 w-5"/></span><div className="flex-1"><p className="text-xs font-semibold uppercase tracking-[.16em] text-indigo-300">Saya peminjam</p><h2 className="mt-2 text-xl font-bold">Lihat status pinjamanmu</h2><p className="mt-2 text-sm leading-6 text-slate-400">Cari nama dan masukkan kode akses untuk melihat semua pinjaman.</p></div><ArrowRight className="mt-1 h-5 w-5 text-slate-500 transition group-hover:translate-x-1 group-hover:text-white"/></div></Link>
        <Link href="/login" className="group rounded-2xl border border-white/10 bg-white/[.04] p-6 backdrop-blur transition hover:-translate-y-1 hover:border-violet-400/40 hover:bg-white/[.08]"><div className="flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-violet-500/20 text-violet-300"><WalletCards className="h-5 w-5"/></span><div className="flex-1"><p className="text-xs font-semibold uppercase tracking-[.16em] text-violet-300">Saya pemberi pinjaman</p><h2 className="mt-2 text-xl font-bold">Kelola catatan pinjaman</h2><p className="mt-2 text-sm leading-6 text-slate-400">Masuk untuk menambah peminjam dan mencatat pembayaran.</p></div><ArrowRight className="mt-1 h-5 w-5 text-slate-500 transition group-hover:translate-x-1 group-hover:text-white"/></div></Link></div></section>
      <footer className="flex items-center justify-center gap-2 text-center text-xs text-slate-500"><LockKeyhole className="h-3.5 w-3.5"/>Data hanya terbuka untuk pihak yang memiliki akses.</footer></div>
  </main>;
}
