"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Save } from "lucide-react";
import { createBorrower } from "@/app/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CurrencyInput } from "@/components/ui/currency-input";
import { DatePicker } from "@/components/ui/date-picker";
import { TagInput } from "@/components/admin/TagInput";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
const Field=({label,name,type="text",required,placeholder}:{label:string;name:string;type?:string;required?:boolean;placeholder?:string})=><div className="space-y-2"><Label htmlFor={name}>{label}{required&&" *"}</Label><Input id={name} name={name} type={type} required={required} placeholder={placeholder}/></div>;
export function NewBorrowerForm(){const router=useRouter();const[loading,setLoading]=useState(false);const[error,setError]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const result=await createBorrower(new FormData(e.currentTarget));setLoading(false);if(result.ok&&result.id){router.push(`/admin/borrowers/${result.id}`);router.refresh()}else if(!result.ok)setError(result.error)}return <form onSubmit={submit} className="space-y-8"><section className="space-y-5"><div><h3 className="font-bold">Informasi peminjam</h3><p className="mt-1 text-sm text-muted-foreground">Data dasar yang membantu mengenali peminjam.</p></div><div className="grid gap-5 sm:grid-cols-2"><Field label="Nama lengkap" name="name" required placeholder="Contoh: Budi Santoso"/><Field label="Nomor WhatsApp" name="phone" placeholder="08123456789"/><div className="sm:col-span-2 space-y-2"><Label>Tag peminjam</Label><TagInput/></div></div></section><div className="border-t"/><section className="space-y-5"><div><h3 className="font-bold">Pinjaman pertama</h3><p className="mt-1 text-sm text-muted-foreground">Jatuh tempo dan bunga boleh dikosongkan.</p></div><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="principal">Jumlah pinjaman *</Label><CurrencyInput id="principal" name="principal" required placeholder="Rp 5.000.000"/></div><Field label="Bunga (%)" name="interest" type="number" placeholder="Opsional"/><div className="space-y-2"><Label htmlFor="startDate">Tanggal mulai *</Label><DatePicker id="startDate" name="startDate" required placeholder="Pilih tanggal mulai"/></div><div className="space-y-2"><Label htmlFor="dueDate">Jatuh tempo</Label><DatePicker id="dueDate" name="dueDate" placeholder="Tidak ditentukan"/></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="description">Keterangan pinjaman</Label><Textarea id="description" name="description" placeholder="Contoh: Modal usaha, kebutuhan keluarga, atau lainnya..."/></div></div></section><div className="rounded-xl border border-indigo-100 bg-indigo-50/70 p-4 text-sm text-indigo-800">Kode verifikasi 6 karakter akan dibuat otomatis setelah data disimpan.</div><div className="space-y-2"><Label htmlFor="notes">Catatan pribadi</Label><Textarea id="notes" name="notes" placeholder="Hanya terlihat oleh pemberi pinjaman."/></div>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex flex-col-reverse gap-3 border-t pt-6 sm:flex-row sm:justify-end"><Button type="button" variant="outline" onClick={()=>router.back()}>Batal</Button><Button disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}{loading?"Menyimpan...":"Simpan peminjam"}</Button></div></form>}
