"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, Save } from "lucide-react";
import { createBorrower } from "@/app/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CurrencyInput } from "@/components/ui/currency-input";
import { TagInput } from "@/components/admin/TagInput";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
const Field=({label,name,type="text",required,placeholder}:{label:string;name:string;type?:string;required?:boolean;placeholder?:string})=><div className="space-y-2"><Label htmlFor={name}>{label}{required&&" *"}</Label><Input id={name} name={name} type={type} required={required} placeholder={placeholder}/></div>;
export function NewBorrowerForm(){const router=useRouter();const[loading,setLoading]=useState(false);const[error,setError]=useState("");async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setLoading(true);setError("");const result=await createBorrower(new FormData(e.currentTarget));setLoading(false);if(result.ok&&result.id){router.push(`/admin/borrowers/${result.id}`);router.refresh()}else if(!result.ok)setError(result.error)}return <form onSubmit={submit} className="space-y-6"><div className="grid gap-5 sm:grid-cols-2"><Field label="Nama lengkap" name="name" required/><Field label="Nomor WhatsApp" name="phone" placeholder="08123456789"/><div className="space-y-2"><Label htmlFor="principal">Jumlah pinjaman *</Label><CurrencyInput id="principal" name="principal" required placeholder="Rp 5.000.000"/></div><Field label="Bunga (%)" name="interest" type="number" placeholder="Opsional"/><Field label="Tanggal mulai" name="startDate" type="date" required/><Field label="Tanggal jatuh tempo (opsional)" name="dueDate" type="date"/></div><p className="rounded-lg bg-blue-50 p-3 text-sm text-blue-700">Kode verifikasi 6 karakter akan dibuat otomatis setelah peminjam disimpan.</p><div className="space-y-2"><Label htmlFor="description">Keterangan pinjaman</Label><Textarea id="description" name="description" placeholder="Keperluan pinjaman..."/></div><div className="space-y-2"><Label>Tag peminjam</Label><TagInput/></div><div className="space-y-2"><Label htmlFor="notes">Catatan pribadi pemberi pinjaman</Label><Textarea id="notes" name="notes" placeholder="Catatan ini tidak terlihat oleh peminjam."/></div>{error&&<p className="rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-3"><Button type="button" variant="outline" onClick={()=>router.back()}>Batal</Button><Button disabled={loading}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<Save className="h-4 w-4"/>}{loading?"Menyimpan...":"Simpan Peminjam"}</Button></div></form>}
