"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Loader2, PlusCircle } from "lucide-react";
import { recordPayment } from "@/app/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { CurrencyInput } from "@/components/ui/currency-input";
import { Label } from "@/components/ui/label";
export function PaymentForm({borrowerId,loanId,remainingAmount}:{borrowerId:string;loanId:string;remainingAmount:number}){const router=useRouter();const[loading,setLoading]=useState(false);const[message,setMessage]=useState<{ok:boolean;text:string}|null>(null);async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setLoading(true);setMessage(null);const result=await recordPayment(borrowerId,loanId,new FormData(form));setLoading(false);if(result.ok){form.reset();setMessage({ok:true,text:"Pembayaran berhasil dicatat."});router.refresh()}else setMessage({ok:false,text:result.error})}return <form onSubmit={submit} className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label htmlFor={`amount-${loanId}`}>Jumlah pembayaran</Label><CurrencyInput id={`amount-${loanId}`} name="amount" required placeholder="Rp 500.000"/><p className="text-xs text-muted-foreground">Maksimal {new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(remainingAmount)}</p></div><div className="space-y-2"><Label htmlFor={`paidAt-${loanId}`}>Tanggal pembayaran</Label><Input id={`paidAt-${loanId}`} name="paidAt" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/></div><div className="space-y-2"><Label htmlFor={`note-${loanId}`}>Catatan</Label><Input id={`note-${loanId}`} name="note" placeholder="Opsional"/></div>{message&&<p className={`sm:col-span-3 rounded-md p-3 text-sm ${message.ok?"bg-emerald-50 text-emerald-700":"bg-red-50 text-red-700"}`}>{message.text}</p>}<div className="sm:col-span-3"><Button disabled={loading||remainingAmount<=0}>{loading?<Loader2 className="h-4 w-4 animate-spin"/>:<PlusCircle className="h-4 w-4"/>}{loading?"Mencatat...":remainingAmount<=0?"Pinjaman sudah lunas":"Catat Pembayaran"}</Button></div></form>}
